### ISSUE TITLE
Cannot create note

### ISSUE THREAD

**Issue by WORMSS** [imkrishnaagrawal/vnotes#1]
First run. Just installed the extension. 

![image](https://user-images.githubusercontent.com/1384537/138841682-a9e5f787-6d85-4f8a-bb96-07a15c3437e9.png)

```
2021-10-26 09:34:45.441] [exthost] [error] Error: EPERM: operation not permitted, open 'test.adoc'
	at Object.openSync (fs.js:476:3)
	at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
	at t.FileProvider.newFile (c:\Users\CRichardson\.vscode\extensions\imkrishnaagrawal.vnotes-0.0.1\dist\extension.js:1:1831)
	at t.NotesProvider.<anonymous> (c:\Users\CRichardson\.vscode\extensions\imkrishnaagrawal.vnotes-0.0.1\dist\extension.js:1:3748)
	at Generator.next (<anonymous>)
	at s (c:\Users\CRichardson\.vscode\extensions\imkrishnaagrawal.vnotes-0.0.1\dist\extension.js:1:2214)
	at processTicksAndRejections (internal/process/task_queues.js:93:5) vnotes.newNote
```

**Comment by renatocfrancisco** [comment]
Test it. Same here.
There should be a proper tutorial too.

**Comment by imkrishnaagrawal** [comment]
Hi @WORMSS, there were some API deprecations that caused issues with the extension. I've applied the necessary fixes and released a new version. You can find it here: [vNotes Extension on Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=KrishnaAgrawal.vnote).
